version: "3.9"

services:
  db:
    image: postgres:16
    container_name: switch-postgres
    restart: always
    environment:
      POSTGRES_USER: javi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: switch
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data